In [1]:
# homework6.ipynb

import numpy as np

# 3.1 - 1D NumPy Arrays

list = [20, 27, 9, 12, 31, 17, 4, 50, 39, 35]

arr = np.array(list)
print("Original array:", arr)

arr_times_4 = arr * 4
print("Each item * 4:", arr_times_4)

mean_val = np.mean(arr)
print("Mean:", mean_val)

median_val = np.median(arr)
print("Median:", median_val)

std_val = np.std(arr)
print("Standard Deviation:", std_val)

smallest_index = np.argmin(arr)
largest_index = np.argmax(arr)
print("Index of smallest:", smallest_index)
print("Index of largest:", largest_index)

print("Smallest value (using index):", arr[smallest_index])
print("Largest value (using index):", arr[largest_index])

smallest_value = np.min(arr)
largest_value = np.max(arr)
print("Smallest value (np.min):", smallest_value)
print("Largest value (np.max):", largest_value)

if arr[smallest_index] == smallest_value and arr[largest_index] == largest_value:
    print("Yes, they match.")
else:
    print("No, they do not match.")

greater_than_20 = arr[arr > 20]
print("Values greater than 20:", greater_than_20)

# 3.2 - 2D NumPy Arrays

matrix = np.array([
[5, 12, 17, 9],
[8, 21, 14, 3],
[6, 13, 19, 11]
])

print("Matrix:\n", matrix)

shape = matrix.shape
print("Shape of matrix:", shape)
print("Number of rows:", shape[0])
print("Number of columns:", shape[1])

third_column = matrix[:, 2]
print("Third column:", third_column)

second_row = matrix[1, :]
print("Second row:", second_row)

matrix_times_2 = matrix * 2
print("Matrix * 2:\n", matrix_times_2)

column_means = np.mean(matrix, axis=0)
print("Mean of each column:", column_means)

overall_mean = np.mean(matrix)
print("Overall mean:", overall_mean)

row_maxes = np.max(matrix, axis=1)
print("Max value in each row:", row_maxes)

column_mins = np.min(matrix, axis=0)
print("Min value in each column:", column_mins)

flattened = matrix.flatten()
print("Flattened array:", flattened)
print("Shape of flattened array:", flattened.shape)

flat_min_index = np.argmin(flattened)
flat_max_index = np.argmax(flattened)
print("Flat index of smallest value:", flat_min_index)
print("Flat index of largest value:", flat_max_index)

min_row, min_col = np.unravel_index(flat_min_index, matrix.shape)
max_row, max_col = np.unravel_index(flat_max_index, matrix.shape)
print("Smallest value is at row", min_row, "and column", min_col)
print("Largest value is at row", max_row, "and column", max_col)

greater_than_15 = matrix[matrix > 15]
print("Values greater than 15:", greater_than_15)

sorted_matrix = np.sort(matrix, axis=1)
print("Sorted rows:\n", sorted_matrix)

def is_prime(n):
    if n < 2:
        return False
    for number in range(2, n):
        if n % number == 0:
            return False
    return True

# 4.0 - Prime Star Systems

arr = np.array([
    [2, 3, 5],
    [14, 6, 8],
    [11, 13, 17],
    [7, 10, 13]
])

def rows_with_at_least_one_prime(arr):
    rows_to_keep = []
    for row in arr:
        has_prime = False
        for value in row:
            if is_prime(value):
                has_prime = True
                break
        if has_prime:
            rows_to_keep.append(row)
    return np.array(rows_to_keep)

filtered_rows = rows_with_at_least_one_prime(arr)
print("Original array:\n", arr)
print("Rows with at least one prime:\n", filtered_rows)

# 5.0 - Let's Play Checkers!
      
def checkerboard():
    board = np.zeros((8, 8), dtype=int)
    for row in range(8):
        for col in range(8):
            if (row + col) % 2 == 0:
                board[row, col] = 1
            else:
                board[row, col] = 0
    return board

def reverse_checkerboard():
    board = np.zeros((8, 8), dtype=int)
    for row in range(8):
        for col in range(8):
            if (row + col) % 2 == 0:
                board[row, col] = 0
            else:
                board[row, col] = 1
    return board

print("Checkerboard (starts with 1):\n", checkerboard())
print("Reverse checkerboard (starts with 0):\n", reverse_checkerboard())

# 6.0 - The Expanding Universe

def expand_string(s, num_spaces):
    if s == "":
        return s
    result = ""
    spaces = " " * num_spaces
    for i in range(len(s)):
        result = result + s[i]
        if i != len(s) - 1:
            result = result + spaces
    return result

def expansion(arr, num_spaces):
    if isinstance(arr, np.ndarray):
        new_list = []
        for word in arr:
            expanded_word = expand_string(word, num_spaces)
            new_list.append(expanded_word)
        return np.array(new_list)
    else:
        return expand_string(arr, num_spaces)

universe = np.array(['galaxy', 'clusters'])
print(expansion(universe, 1))
print(expansion(universe, 2))
print(expansion("hello", 2))

# 7.0 - Second-Brightest Star

def secondDimmest(arr):
    second_values = []
    for row in arr:
        sorted_row = np.sort(row)
        second_largest = sorted_row[-2]
        second_values.append(second_largest)
    return np.array(second_values)

np.random.seed(123)
stars = np.random.randint(500, 2000, (5, 5))
print("Stars array:\n", stars)
print("Second dimmest (second-largest) from each row:\n", secondDimmest(stars))

Original array: [20 27  9 12 31 17  4 50 39 35]
Each item * 4: [ 80 108  36  48 124  68  16 200 156 140]
Mean: 24.4
Median: 23.5
Standard Deviation: 13.828955130450023
Index of smallest: 6
Index of largest: 7
Smallest value (using index): 4
Largest value (using index): 50
Smallest value (np.min): 4
Largest value (np.max): 50
Yes, they match.
Values greater than 20: [27 31 50 39 35]
Matrix:
 [[ 5 12 17  9]
 [ 8 21 14  3]
 [ 6 13 19 11]]
Shape of matrix: (3, 4)
Number of rows: 3
Number of columns: 4
Third column: [17 14 19]
Second row: [ 8 21 14  3]
Matrix * 2:
 [[10 24 34 18]
 [16 42 28  6]
 [12 26 38 22]]
Mean of each column: [ 6.33333333 15.33333333 16.66666667  7.66666667]
Overall mean: 11.5
Max value in each row: [17 21 19]
Min value in each column: [ 5 12 14  3]
Flattened array: [ 5 12 17  9  8 21 14  3  6 13 19 11]
Shape of flattened array: (12,)
Flat index of smallest value: 7
Flat index of largest value: 5
Smallest value is at row 1 and column 3
Largest value is at row 1 and col